user-list:
  - name: azami
    pass: bigrandomunguessablepassword
    shell: /bin/zsh
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAexMgLoJmyKkUa3MYqBCrvpnGbkpCy9N5HPFyujes2gAAP/EABwQAAEDBQAAAAAAAAAAAAAAABARICEAATAxQf/aAAgBAQABBQJ6hT0aNxFQxMf/xAAVEQEBAAAAAAAAAAAAAAAAAABAAf/aAAgBAwEBPwEUF//EABoRAAIDAQEAAAAAAAAAAAAAAAEQABEgITD/2gAIAQIBAT8Blq2cBHRXJzFef//EABQQAQAAAAAAAAAAAAAAAAAAAFD/2gAIAQEABj8CE//EAB4QAAIBBAMBAAAAAAAAAAAAAAABERAxQVEgIYEw/9oACAEBAAE/ISdHvB6OlITBmjDl2EoUCWFh0uk6V0TsydGxLFLj9ECWhKPh/9oADAMBAAIAAwAAABCf8RCrSu8SpIQeDySST//EAB0RAAICAQUAAAAAAAAAAAAAAAERABAhIDAxQVH/2gAIAQMBAT8Qi9rFgd2omKHGsjMxGHAsEGmBCXsf/8QAHREAAwACAgMAAAAAAAAAAAAAAAERECExQTBRYf/aAAgBAgEBPxA+Dfspcidw/QilGjxzEUtyvYmmt4VBbeHsbLjEbEp4P//EACIQAQACAQQCAgMAAAAAAAAAAAEAESEQMUFhUZEwcYGhwf/aAAgBAQABPxCWf6lMWncESzR5PaIqNh54g2WTYMvXEGujospQqlO7AobRFWS/UWNDQ4MHEn2aK8CO2XJ7aICnaOcUlfLHdn5YZ75fg//Z
  - name: malik
    pass: anotherhardtoguesspassword
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAexMgLoJmyKkC63MYqBCrvpnGbktkLnXTeRzxVI3qWgAAP/EABkQAAIDAQAAAAAAAAAAAAAAABARASAwQf/aAAgBAQABBQLToRm6z//EABcRAAMBAAAAAAAAAAAAAAAAAAERMED/2gAIAQMBAT8BxCCl/8QAGhEAAgMBAQAAAAAAAAAAAAAAAREAECAwMf/aAAgBAgEBPwGOnZwKOjSyo57x/8QAFRABAQAAAAAAAAAAAAAAAAAAQEH/2gAIAQEABj8CJQf/xAAeEAADAAEEAwAAAAAAAAAAAAAAARFREDFBgSAhMP/aAAgBAQABPyEuDvweCxFKmc6MNUSigoHpuopg9BzD7EuNNxivJGxKfD//2gAMAwEAAgADAAAAEJ/xFHdKTxLrRBy/JJJP/8QAHREAAgMAAgMAAAAAAAAAAAAAAAEQESEgMDFBUf/aAAgBAwEBPxAr7GSl7misheOZ4WzR4ptMoYhu+j//xAAdEQADAAICAwAAAAAAAAAAAAAAAREQITFBMFFh/9oACAECAQE/ED4N+ylyJ3D9FKUaPHMsKXK9ijRBEhbeHsbLgojCU8H/xAAgEAEAAgEEAgMAAAAAAAAAAAABABEhEEFhkVFxMDHB/9oACAEBAAE/EJZ/Upi05giWaPJ2iLFogEsbIMQRqDXB0WUwc4JYB9QGI7ZixoaGxgtS7NxlRo3vaXJ20QFP1EOTySjd1BFgr5YZ53fg/9k=
  - name: anima
    pass: wewillencryptthislater
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAexMgLoJmyKkC63MYqBCrvpnGbkpCy9N5HPFyujes2gAAP/EABsQAAEEAwAAAAAAAAAAAAAAABAAESEwASBB/9oACAEBAAEFArOhjkQo0av/xAAVEQEBAAAAAAAAAAAAAAAAAABAAf/aAAgBAwEBPwEUF//EABoRAAIDAQEAAAAAAAAAAAAAAAEQABEgITD/2gAIAQIBAT8Blq2cBHRXJzFef//EABQQAQAAAAAAAAAAAAAAAAAAAFD/2gAIAQEABj8CE//EAB4QAAMAAQQDAAAAAAAAAAAAAAABEVEQMUGBICEw/9oACAEBAAE/IS4O/B4LEUqZzow1RKKCgem6npbouTLg2Jcabj7EEsCU+H//2gAMAwEAAgADAAAAEJ/xFHdKTxKkhB4PJJJP/8QAHREAAgMAAgMAAAAAAAAAAAAAAREAECEgMDFBUf/aAAgBAwEBPxCL7WWB7tRZQ8cyM2Iw4LBBpgQl9H//xAAdEQADAAICAwAAAAAAAAAAAAAAAREQITFBMFFh/9oACAECAQE/ED4N+ylyJ3D9FKUaPHMsKXK9iaa3hUFt4exsuMRsSng//8QAIRABAAIBAwQDAAAAAAAAAAAAAQARIRBBYTAxcZFRgcH/2gAIAQEAAT8Qln9SmLTmCJZo8ntEWLRAJY2QYgjUGuDospg5wSwD4gMR2zFjQ0NjBxJ5NFdhHLLk9tEBT2jm1JX5Y+z7YZ53eh//2Q==
  - name: zahara
    pass: tooeasytoguess
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAdhZAD0BZsw0SsrcjFIZI1vpmM2RiHLpvIZ4srResugAAAP/xAAcEAABBAMBAAAAAAAAAAAAAAABABAgIREwMUH/2gAIAQEAAQUCmeBAv7EtSqGNf//EABURAQEAAAAAAAAAAAAAAAAAAEAB/9oACAEDAQE/ARQX/8QAGhEAAgMBAQAAAAAAAAAAAAAAARAAESAhMP/aAAgBAgEBPwGWrZwEdFcnMV5//8QAFBABAAAAAAAAAAAAAAAAAAAAUP/aAAgBAQAGPwIT/8QAHhAAAgEEAwEAAAAAAAAAAAAAAAERECExUSBBgTD/2gAIAQEAAT8hJ0e8HoaLBpRI2d0Yd0KyEobHTKSyyidmTo2JdUyP0QJaEo+H/9oADAMBAAIAAwAAABCf8RTrSk0SpIQeDySST//EAB0RAAIDAAIDAAAAAAAAAAAAAAERABAhIDAxQVH/2gAIAQMBAT8Qi+1lge7UWUPHMjNiMOCwQaYEJfR//8QAHREBAAICAgMAAAAAAAAAAAAAAQAQESExQTBRYf/aAAgBAgEBPxCfE37mRzBzT6gzMWLDXOFLZ7gibpkQ207ijisLAx4P/8QAIRABAAIBBAIDAQAAAAAAAAAAAQARMRAhQWFRkTBxgcH/2gAIAQEAAT8Qln+pTFp3BEs0e57RbMsEoVyxgOOINdHRboNsYKDxL5eYttDQ4MHaT7NFeBHbLk9tEBTiOcUlfLH4frDPfL8H/9k=

default_picture: !!binary |
    /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////
    ////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////
    ////////////////////////////////////////////////////////////wgARCAAqACoDAREA
    AhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/
    2gAMAwEAAhADEAAAAexMgLoJmyKkUa3MYqKQLvpnGbkpCy9N5HPFyujes2gAAP/EABsQAAAHAQAA
    AAAAAAAAAAAAAAABEBEgITBB/9oACAEBAAEFAtOxNKFQbP8A/8QAFREBAQAAAAAAAAAAAAAAAAAA
    QAH/2gAIAQMBAT8BFBf/xAAaEQACAwEBAAAAAAAAAAAAAAABEAARICEw/9oACAECAQE/AZatnAR0
    VycxXn//xAAUEAEAAAAAAAAAAAAAAAAAAABQ/9oACAEBAAY/AhP/xAAeEAACAQQDAQAAAAAAAAAA
    AAAAAREQITFRIEGBMP/aAAgBAQABPyEnR7weiYVJTO6MNShWQlA6ZSWWUTsydGxLqmR+iBLQlHw/
    /9oADAMBAAIAAwAAABCf8RTzSkkSpIQeDySST//EAB0RAAIDAAIDAAAAAAAAAAAAAAERABAhIDAx
    QVH/2gAIAQMBAT8Qi+1lge7UWUPHMjNiMOCwQaYEJfR//8QAHREAAgIDAAMAAAAAAAAAAAAAAAEQ
    ESExQTBRYf/aAAgBAgEBPxA+DPsstidw/BMssanG5qLleiaazC0Flw8jZaimxKvB/8QAIRABAAIB
    BAEFAAAAAAAAAAAAAQARQRAhMWGRMFFxgcH/2gAIAQEAAT8Qln9SmLTuCJZo9zyiLFogiWcQYg2k
    Gujot0Cq4KA4ILUzFtoaGDB2k+TRXAjtlyeWiAp4jmKSvux8PthnvL6H/9k=