#!jinja|yaml|gpg
user-list:
  - name: azami
    pass: |
      -----BEGIN PGP MESSAGE-----

      hQEMA3Vh5Rp82+a5AQf/Y5xirqUXmyGW4oSh5GEfdt2LCwGw41o9lkTL6tQ0O6cn
      rAi4x+KN72XVriasRGhfiIniFJ8ilPPVJO3jcTqN3n6fdjib0bnBC+er7GYTF/t4
      DH07A42UWMFV7NehGaE1MGi3TtQuwCzYdkw/uYpoyQq9mRXn7q0e2UlSikUyYplP
      /H5dbIyxpD2Nr+PiIstJtUllgxgMo/vtFrfUHzvSypPU5ZshuJz4LdZ3Bhi1jo1r
      28eNdF2Wsmcrp+7E80LqORu8mOn1m9A8PIstd8+V02CPPC+w5yZUQgjpyj0fDlNp
      TYGtWcJKubEqQ9CUgsrsMhoeLWgkfoNcZwXLF6xFedJYAWfQvo8pUDKl/++abE50
      J6kxL4DCpsnWKZszQ1tLhJAg54KN0ykv1nNkazt5S1wolUi/LJVuUDGx9Aow90Fl
      Gj74faCaU+gEB9nTi6u1KRS7rbK5AwgGPA==
      =LCG7
      -----END PGP MESSAGE-----
    shell: /bin/zsh
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAexMgLoJmyKkUa3MYqBCrvpnGbkpCy9N5HPFyujes2gAAP/EABwQAAEDBQAAAAAAAAAAAAAAABARICEAATAxQf/aAAgBAQABBQJ6hT0aNxFQxMf/xAAVEQEBAAAAAAAAAAAAAAAAAABAAf/aAAgBAwEBPwEUF//EABoRAAIDAQEAAAAAAAAAAAAAAAEQABEgITD/2gAIAQIBAT8Blq2cBHRXJzFef//EABQQAQAAAAAAAAAAAAAAAAAAAFD/2gAIAQEABj8CE//EAB4QAAIBBAMBAAAAAAAAAAAAAAABERAxQVEgIYEw/9oACAEBAAE/ISdHvB6OlITBmjDl2EoUCWFh0uk6V0TsydGxLFLj9ECWhKPh/9oADAMBAAIAAwAAABCf8RCrSu8SpIQeDySST//EAB0RAAICAQUAAAAAAAAAAAAAAAERABAhIDAxQVH/2gAIAQMBAT8Qi9rFgd2omKHGsjMxGHAsEGmBCXsf/8QAHREAAwACAgMAAAAAAAAAAAAAAAERECExQTBRYf/aAAgBAgEBPxA+Dfspcidw/QilGjxzEUtyvYmmt4VBbeHsbLjEbEp4P//EACIQAQACAQQCAgMAAAAAAAAAAAEAESEQMUFhUZEwcYGhwf/aAAgBAQABPxCWf6lMWncESzR5PaIqNh54g2WTYMvXEGujospQqlO7AobRFWS/UWNDQ4MHEn2aK8CO2XJ7aICnaOcUlfLHdn5YZ75fg//Z
  - name: malik
    pass: |
      -----BEGIN PGP MESSAGE-----

      hQEMA3Vh5Rp82+a5AQf+IpX/NmRGl7rPZNPy+Ykpsx+0OViRfCuqFh5N+DOQQRmQ
      MPkv3bS8TpaasmDya767rHDyKkxSk2BIIjghCDFoEj7yjmPpl/bclnQ/Nt0io/hL
      3+ABFGqUjgipZGCcy2h3vgAGLAfPfCKFixYvsGAOIxUIiXFbWSu8Lb+GvoHT/L9d
      DalkhCThX1okP42MGl+qtmhS9UxYiq3cmQIuPBj3Q+EGmJHUd7YaECc2NaaHH8Ro
      c0/uOVSr1tUFD3qQk4E/uIoz5hNlD8ZZPKVTq3bAFD2CCAAKbEnfLtX3bPiuw27i
      t0I7oGldMDUSR1nwNpAql8e7Wc8u2zGGLlBtuzGkDNJWAdi93EM5TYlQiKlLL4Ee
      HpphQpVB1Uq1t2MJmObcg1oEY9qPB9Ze70mCZAN47PHn74Vve9QByQjBWX/q+GaH
      BGPfV5DnV6wAkFivoatdTSws0G3N70o=
      =npDN
      -----END PGP MESSAGE-----
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAexMgLoJmyKkC63MYqBCrvpnGbktkLnXTeRzxVI3qWgAAP/EABkQAAIDAQAAAAAAAAAAAAAAABARASAwQf/aAAgBAQABBQLToRm6z//EABcRAAMBAAAAAAAAAAAAAAAAAAERMED/2gAIAQMBAT8BxCCl/8QAGhEAAgMBAQAAAAAAAAAAAAAAAREAECAwMf/aAAgBAgEBPwGOnZwKOjSyo57x/8QAFRABAQAAAAAAAAAAAAAAAAAAQEH/2gAIAQEABj8CJQf/xAAeEAADAAEEAwAAAAAAAAAAAAAAARFREDFBgSAhMP/aAAgBAQABPyEuDvweCxFKmc6MNUSigoHpuopg9BzD7EuNNxivJGxKfD//2gAMAwEAAgADAAAAEJ/xFHdKTxLrRBy/JJJP/8QAHREAAgMAAgMAAAAAAAAAAAAAAAEQESEgMDFBUf/aAAgBAwEBPxAr7GSl7misheOZ4WzR4ptMoYhu+j//xAAdEQADAAICAwAAAAAAAAAAAAAAAREQITFBMFFh/9oACAECAQE/ED4N+ylyJ3D9FKUaPHMsKXK9ijRBEhbeHsbLgojCU8H/xAAgEAEAAgEEAgMAAAAAAAAAAAABABEhEEFhkVFxMDHB/9oACAEBAAE/EJZ/Upi05giWaPJ2iLFogEsbIMQRqDXB0WUwc4JYB9QGI7ZixoaGxgtS7NxlRo3vaXJ20QFP1EOTySjd1BFgr5YZ53fg/9k=
  - name: anima
    pass: |
      -----BEGIN PGP MESSAGE-----

      hQEMA3Vh5Rp82+a5AQf8CKHppWV8sj4IkVoXdlwAEuHF4n0ouLCYXYJqzVBKolxR
      MY8dZ/7dZiZs0+ik4yjO62G+RH2h6Ygehna9/284h5B/8ajRJu1qsA+fZsXx7PiZ
      WbXlaRMN7muTV65AdJFU02OFHmvQBWHAOwEptpMPnO+uaEj3cjNnfyjYmt8zv+LS
      Mp6yfDtjFRioBGKc3YPCspS/WHbgDdLEbaMXC3BXCFOEQDkZMDsUoHgLqiKvcgme
      +A+iGXhU9DeSzLZJxU4kBNKdZ9yW3vSv1QNV2Rb7Ob2zCpfG4zR0T8koCVD9Z1Pt
      rakaAiEBP4Bhf2MAAg/eARdpjOY/Xw7scItYdQ1QXNJSAcRcWK8VxcIjZp+zmfzV
      I0lGkdFxz5aEEox2vN37FIoPEBABKvatZ8qCi4Ezvz+oz82yNxxiq1gy0QS584so
      eRz9xa+ITp7ZHbzasJL/+62jyw==
      =BuCu
      -----END PGP MESSAGE-----
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAexMgLoJmyKkC63MYqBCrvpnGbkpCy9N5HPFyujes2gAAP/EABsQAAEEAwAAAAAAAAAAAAAAABAAESEwASBB/9oACAEBAAEFArOhjkQo0av/xAAVEQEBAAAAAAAAAAAAAAAAAABAAf/aAAgBAwEBPwEUF//EABoRAAIDAQEAAAAAAAAAAAAAAAEQABEgITD/2gAIAQIBAT8Blq2cBHRXJzFef//EABQQAQAAAAAAAAAAAAAAAAAAAFD/2gAIAQEABj8CE//EAB4QAAMAAQQDAAAAAAAAAAAAAAABEVEQMUGBICEw/9oACAEBAAE/IS4O/B4LEUqZzow1RKKCgem6npbouTLg2Jcabj7EEsCU+H//2gAMAwEAAgADAAAAEJ/xFHdKTxKkhB4PJJJP/8QAHREAAgMAAgMAAAAAAAAAAAAAAREAECEgMDFBUf/aAAgBAwEBPxCL7WWB7tRZQ8cyM2Iw4LBBpgQl9H//xAAdEQADAAICAwAAAAAAAAAAAAAAAREQITFBMFFh/9oACAECAQE/ED4N+ylyJ3D9FKUaPHMsKXK9iaa3hUFt4exsuMRsSng//8QAIRABAAIBAwQDAAAAAAAAAAAAAQARIRBBYTAxcZFRgcH/2gAIAQEAAT8Qln9SmLTmCJZo8ntEWLRAJY2QYgjUGuDospg5wSwD4gMR2zFjQ0NjBxJ5NFdhHLLk9tEBT2jm1JX5Y+z7YZ53eh//2Q==
  - name: zahara
    pass: |
      -----BEGIN PGP MESSAGE-----

      hQEMA3Vh5Rp82+a5AQgAn6fG9B785DDTaZdP1VEBcpMuVrdRgxn04zPnIDCUDxD8
      cYheKYOne7e/dKjU38zE8HgJbvYZp7iczhKZW+CfyBRBvKu6gu64kxNT1TAvIkVs
      tPeNyckb/vUb729W7bmyYL6r35h7TKLy5gJmycsgPTZUkuY28gZJN/NcUK0rdApw
      mihWrzw3pewNPPtQgNeuH+3HB0bf9DqjR/6SRP9unqRI3PLBnwMrFTkBUIdEY6bt
      cRYsZ67pc1s2c9Fuq2vZKzXMYx05KNBznRsQF5h+uty8Bvl7eDAwb3HlHVm8VqsO
      W6WMlTWU4BfSGrzjgeya8qnh06U7keunmXh2dD3g/dJKAauIPjpYxN9Urs1EUsc9
      KlFK/X2+xuN3HQfbTuWC56bVKEHCLFE5M8Qi21gsnWmmFLu4//6SoId5YaQFVuak
      G0sSihA3Y6qmwU8=
      =Z9Ff
      -----END PGP MESSAGE-----
    picture: !!binary /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////////////////////////////////////////////////////////////////wgARCAAqACoDAREAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAdhZAD0BZsw0SsrcjFIZI1vpmM2RiHLpvIZ4srResugAAAP/xAAcEAABBAMBAAAAAAAAAAAAAAABABAgIREwMUH/2gAIAQEAAQUCmeBAv7EtSqGNf//EABURAQEAAAAAAAAAAAAAAAAAAEAB/9oACAEDAQE/ARQX/8QAGhEAAgMBAQAAAAAAAAAAAAAAARAAESAhMP/aAAgBAgEBPwGWrZwEdFcnMV5//8QAFBABAAAAAAAAAAAAAAAAAAAAUP/aAAgBAQAGPwIT/8QAHhAAAgEEAwEAAAAAAAAAAAAAAAERECExUSBBgTD/2gAIAQEAAT8hJ0e8HoaLBpRI2d0Yd0KyEobHTKSyyidmTo2JdUyP0QJaEo+H/9oADAMBAAIAAwAAABCf8RTrSk0SpIQeDySST//EAB0RAAIDAAIDAAAAAAAAAAAAAAERABAhIDAxQVH/2gAIAQMBAT8Qi+1lge7UWUPHMjNiMOCwQaYEJfR//8QAHREBAAICAgMAAAAAAAAAAAAAAQAQESExQTBRYf/aAAgBAgEBPxCfE37mRzBzT6gzMWLDXOFLZ7gibpkQ207ijisLAx4P/8QAIRABAAIBBAIDAQAAAAAAAAAAAQARMRAhQWFRkTBxgcH/2gAIAQEAAT8Qln+pTFp3BEs0e57RbMsEoVyxgOOINdHRboNsYKDxL5eYttDQ4MHaT7NFeBHbLk9tEBTiOcUlfLH4frDPfL8H/9k=

default_picture: !!binary |
    /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////
    ////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////
    ////////////////////////////////////////////////////////////wgARCAAqACoDAREA
    AhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/
    2gAMAwEAAhADEAAAAexMgLoJmyKkUa3MYqKQLvpnGbkpCy9N5HPFyujes2gAAP/EABsQAAAHAQAA
    AAAAAAAAAAAAAAABEBEgITBB/9oACAEBAAEFAtOxNKFQbP8A/8QAFREBAQAAAAAAAAAAAAAAAAAA
    QAH/2gAIAQMBAT8BFBf/xAAaEQACAwEBAAAAAAAAAAAAAAABEAARICEw/9oACAECAQE/AZatnAR0
    VycxXn//xAAUEAEAAAAAAAAAAAAAAAAAAABQ/9oACAEBAAY/AhP/xAAeEAACAQQDAQAAAAAAAAAA
    AAAAAREQITFRIEGBMP/aAAgBAQABPyEnR7weiYVJTO6MNShWQlA6ZSWWUTsydGxLqmR+iBLQlHw/
    /9oADAMBAAIAAwAAABCf8RTzSkkSpIQeDySST//EAB0RAAIDAAIDAAAAAAAAAAAAAAERABAhIDAx
    QVH/2gAIAQMBAT8Qi+1lge7UWUPHMjNiMOCwQaYEJfR//8QAHREAAgIDAAMAAAAAAAAAAAAAAAEQ
    ESExQTBRYf/aAAgBAgEBPxA+DPsstidw/BMssanG5qLleiaazC0Flw8jZaimxKvB/8QAIRABAAIB
    BAEFAAAAAAAAAAAAAQARQRAhMWGRMFFxgcH/2gAIAQEAAT8Qln9SmLTuCJZo9zyiLFogiWcQYg2k
    Gujot0Cq4KA4ILUzFtoaGDB2k+TRXAjtlyeWiAp4jmKSvux8PthnvL6H/9k=
